# Site settings
title:       Abe Voelker
email:       _@abevoelker.com
author:      Abe Voelker
baseurl:     ""
url:         "https://abevoelker.com"
date_format: "%b %-d, %Y"

author:
  name: "Abe Voelker"
  home: "/"
  avatar: "bio-photo.jpg"
  bio: "Programming, guns, ISP/telecom, rural life. Ex-farm boy"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:_@abevoelker.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/abevoelker"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/abevoelker"

og_image: "bio-photo.jpg"
twitter:
  username: "abevoelker"
social:
  name: Abe Voelker
  type: Person
  links:
    - "https://twitter.com/abevoelker"
    - "https://github.com/abevoelker"
    - "https://www.facebook.com/abe.voelker"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      comments: false
      share: true
      related: false
      # Disable excerpts
      excerpt: ""

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-16891019-1"
    anonymize_ip: false # default

comments:
  provider: "disqus"
  disqus:
    shortname: "abevoelker"

after_footer_scripts:
  - "//platform.twitter.com/widgets.js"

# Build settings
markdown:     kramdown
kramdown:
  # disable smart quotes
  smart_quotes: ["apos", "apos", "quot", "quot"]
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    '/:title/'
timezone: "America/Chicago"
sass:
  compressed: true
theme: minimal-mistakes-jekyll
plugins:
  #- jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-toc
  - jekyll-include-cache
  - jekyll-feed
# https://github.com/jekyll/jekyll/issues/2938
exclude: ["vendor", "Gemfile*", "deploy.sh", "_private"]
include: [".well-known"]
assets:
  sources:
    - _assets/css
    - _assets/fonts
    - _assets/images
    - _assets/videos
    - _assets/javascript
    - _assets/video
    - _assets/image
    - _assets/img
    - _assets/js
    - _assets/other
